import { StyleSheet } from 'react-native';
import { Spacing, FontWeight } from '../../../constants/theme';

const R = 2;
export const s = StyleSheet.create({
  root: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.md,
    borderBottomWidth: 1,
  },
  headerCopy: { flex: 1, gap: 2 },
  headerTitle: { fontSize: 14, fontWeight: FontWeight.black, letterSpacing: 1.4 },
  headerSub: { fontSize: 9, fontWeight: FontWeight.black, letterSpacing: 1.2 },
  closeBtn: { width: 28, height: 28, alignItems: 'center', justifyContent: 'center' },
  scroll: { padding: Spacing.base, gap: Spacing.md, paddingBottom: Spacing.xxxl },
  deviceCard: {
    borderWidth: 1,
    borderRadius: R,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    gap: 4,
  },
  sectionLabel: { fontSize: 8, fontWeight: FontWeight.black, letterSpacing: 1.8 },
  deviceText: { fontSize: 12, fontWeight: FontWeight.black, letterSpacing: 0.3, lineHeight: 18 },
  fieldBlock: { gap: Spacing.xs },
  fieldLabel: { fontSize: 8, fontWeight: FontWeight.black, letterSpacing: 1.8 },
  descInput: {
    borderWidth: 1,
    borderRadius: R,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    fontSize: 13,
    minHeight: 120,
    lineHeight: 20,
  },
  hint: { fontSize: 10, fontWeight: '500', lineHeight: 15, opacity: 0.85 },
  imagesLabelRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  imagesCount: { fontSize: 9, fontWeight: FontWeight.black, letterSpacing: 1 },
  imagesGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.xs },
  imageSlot: {
    width: 72,
    height: 72,
    borderRadius: R,
    borderWidth: 1,
    overflow: 'hidden',
  },
  imageThumb: { width: '100%', height: '100%' },
  imageRemove: {
    position: 'absolute',
    top: 3,
    right: 3,
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    opacity: 0.9,
  },
  addSlot: {
    width: 72,
    height: 72,
    borderRadius: R,
    borderWidth: 1,
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  addSlotText: { fontSize: 6, fontWeight: FontWeight.black, letterSpacing: 0.8, textAlign: 'center' },
  imageActionRow: {
    flexDirection: 'row',
    gap: Spacing.xs,
    marginTop: Spacing.xs,
  },
  imageActionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 1,
    borderRadius: R,
    paddingVertical: 13,
    paddingHorizontal: Spacing.sm,
  },
  imageActionText: { fontSize: 11, fontWeight: FontWeight.black, letterSpacing: 1 },
  sourcePicker: {
    borderWidth: 1,
    borderRadius: R,
    padding: Spacing.sm,
    gap: Spacing.xs,
    minWidth: 140,
  },
  sourceBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderRadius: R,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 7,
  },
  sourceBtnText: { fontSize: 10, fontWeight: FontWeight.black, letterSpacing: 0.8 },
  sourceCancelText: { fontSize: 9, fontWeight: FontWeight.black, letterSpacing: 1, textAlign: 'center', paddingVertical: 2 },
  submitBtn: {
    borderRadius: R,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: Spacing.sm,
  },
  submitBtnDisabled: { opacity: 0.6 },
  submitBtnText: { fontSize: 12, fontWeight: FontWeight.black, letterSpacing: 1.5 },
  reportsHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: Spacing.sm },
  reportsRefresh: { fontSize: 9, fontWeight: FontWeight.black, letterSpacing: 1.2 },
  reportRow: { borderTopWidth: 1, paddingTop: Spacing.sm, gap: 4 },
  reportDate: { fontSize: 9, fontWeight: FontWeight.black, letterSpacing: 0.8 },
  reportDesc: { fontSize: 12, fontWeight: FontWeight.black, lineHeight: 18 },
  reportMeta: { fontSize: 10, fontWeight: '600', lineHeight: 15 },
});

