import { StyleSheet } from 'react-native';
import { FontWeight, Spacing } from '../../../constants/theme';

export const styles = StyleSheet.create({
  root: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.md,
    borderBottomWidth: 1,
  },
  headerCopy: { flex: 1, gap: 2 },
  headerTitle: { fontSize: 14, fontWeight: FontWeight.black, letterSpacing: 1.2 },
  headerSub: { fontSize: 9, fontWeight: FontWeight.black, letterSpacing: 1 },
  closeBtn: { width: 28, height: 28, alignItems: 'center', justifyContent: 'center' },
  scroll: { padding: Spacing.base, gap: Spacing.sm, paddingBottom: Spacing.xxxl },
  filterRowWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.xs },
  filterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderRadius: 2,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 10,
  },
  filterChipText: { fontSize: 10, fontWeight: FontWeight.black, letterSpacing: 0.8 },
  filterChipCount: { fontSize: 10, fontWeight: FontWeight.black },
  refreshBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 1,
    borderRadius: 2,
    paddingVertical: 12,
  },
  refreshText: { fontSize: 11, fontWeight: FontWeight.black, letterSpacing: 1 },
  loader: { marginTop: Spacing.sm },
  errorText: { fontSize: 12, fontWeight: FontWeight.bold },
  card: {
    borderWidth: 1,
    borderRadius: 2,
    padding: Spacing.md,
    gap: Spacing.sm,
  },
  emptyText: { fontSize: 12, fontWeight: FontWeight.bold },
  cardHead: { flexDirection: 'row', justifyContent: 'space-between', gap: Spacing.sm },
  cardHeadCopy: { flex: 1, gap: 3 },
  reportUser: { fontSize: 12, fontWeight: FontWeight.black, letterSpacing: 0.8 },
  reportMeta: { fontSize: 10, fontWeight: '700' },
  statusPill: {
    borderWidth: 1,
    borderRadius: 2,
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  statusPillText: { fontSize: 9, fontWeight: FontWeight.black, letterSpacing: 0.8 },
  reportDesc: { fontSize: 13, fontWeight: FontWeight.black, lineHeight: 20 },
  imagesRow: { gap: Spacing.xs },
  reportImage: { width: 120, height: 120, borderRadius: 2 },
  metaGrid: { gap: 4 },
  metaText: { fontSize: 10, fontWeight: '600', lineHeight: 15 },
  actionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.xs, alignItems: 'center' },
  actionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderRadius: 2,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 10,
  },
  actionText: { fontSize: 10, fontWeight: FontWeight.black, letterSpacing: 0.7 },
});
