import { StyleSheet } from 'react-native';
import { Spacing, FontSize, FontWeight } from '../../../constants/theme';

export const styles = StyleSheet.create({
  wrapper: { flex: 1 },
  overlay: { flex: 1, justifyContent: 'center', paddingHorizontal: 12, paddingVertical: 16 },
  overlayBackdrop: { ...StyleSheet.absoluteFillObject },
  modalViewport: { flex: 1, width: '100%', alignItems: 'center', justifyContent: 'center' },
  modalCard: { width: '100%', maxWidth: 455, maxHeight: '92%', minHeight: 420, borderWidth: 1 },
  screen: { flex: 1 },
  flex: { flex: 1 },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 22,
    paddingVertical: 18,
    borderBottomWidth: 1,
  },
  headerTitle: { fontSize: 14, fontWeight: FontWeight.black, letterSpacing: 1.4 },
  closeBtn: { width: 24, height: 24, alignItems: 'center', justifyContent: 'center' },
  scroll: { flex: 1 },
  content: { paddingHorizontal: 22, paddingVertical: 20, gap: Spacing.md, paddingBottom: 22 },
  typeToggle: { flexDirection: 'row', borderWidth: 1, borderRadius: 2, padding: 3, gap: 3 },
  typeBtn: { flex: 1, paddingVertical: 9, alignItems: 'center', justifyContent: 'center', borderRadius: 2 },
  typeBtnText: { fontSize: 11, fontWeight: FontWeight.black, letterSpacing: 0.6 },
  goalToggle: { flexDirection: 'row', gap: 3, borderWidth: 1, borderRadius: 2, padding: 3 },
  goalBtn: { flex: 1, borderWidth: 1, borderColor: 'transparent', borderRadius: 2, paddingVertical: 8, alignItems: 'center', justifyContent: 'center' },
  goalBtnText: { fontSize: 10, fontWeight: FontWeight.black, letterSpacing: 0.45 },
  customPeriodInput: { marginTop: Spacing.sm },
  ticketBlock: { borderWidth: 1, borderRadius: 2, padding: Spacing.base, gap: Spacing.sm },
  ticketHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: Spacing.sm },
  ticketTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  ticketTitle: { fontSize: FontSize.sm, fontWeight: FontWeight.black, letterSpacing: 0.6 },
  ticketConfidence: { fontSize: FontSize.xs, fontWeight: FontWeight.black },
  ticketHint: { fontSize: FontSize.xs, lineHeight: 18 },
  ticketActions: { flexDirection: 'row', gap: Spacing.sm },
  ticketActionBtn: { flex: 1, borderWidth: 1, borderRadius: 2, paddingVertical: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
  ticketActionText: { fontSize: FontSize.xs, fontWeight: FontWeight.black, letterSpacing: 0.3 },
  ticketPreview: { borderWidth: 1, borderRadius: 2, padding: Spacing.sm, flexDirection: 'row', gap: Spacing.sm, alignItems: 'center' },
  ticketPreviewImage: { width: 56, height: 56, borderRadius: 2 },
  ticketPreviewCopy: { flex: 1, gap: 2 },
  ticketPreviewTitle: { fontSize: FontSize.xs, fontWeight: FontWeight.black, letterSpacing: 0.4 },
  ticketPreviewMeta: { fontSize: FontSize.xs, lineHeight: 16 },
  ticketRemaining: { fontSize: 10, fontWeight: FontWeight.bold, marginTop: 2 },
  field: { gap: Spacing.xs },
  label: { fontSize: FontSize.xs, fontWeight: FontWeight.black, letterSpacing: 1 },
  amountRow: { flexDirection: 'row', gap: 0, alignItems: 'stretch', borderWidth: 1, borderRadius: 2, overflow: 'hidden', minHeight: 52 },
  currencyPill: { width: 80, borderRightWidth: 1, alignItems: 'center', justifyContent: 'center', gap: 1 },
  currencyPillButton: { paddingVertical: 4 },
  currencyCode: { fontSize: 10, fontWeight: FontWeight.black, letterSpacing: 1 },
  currencySymbol: { fontSize: FontSize.base, fontWeight: FontWeight.black },
  input: { fontSize: FontSize.base, paddingHorizontal: Spacing.md, paddingVertical: Spacing.md, borderRadius: 2, borderWidth: 1 },
  amountInput: { flex: 1, fontSize: FontSize.lg, fontWeight: FontWeight.black, textAlign: 'center', borderWidth: 0, borderRadius: 0, paddingVertical: 12 },
  paymentRow: { flexDirection: 'row', gap: Spacing.sm },
  paymentBtn: { flex: 1, borderWidth: 1, borderRadius: 2, minHeight: 44, paddingVertical: 6, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
  paymentBtnText: { fontSize: 10, fontWeight: FontWeight.black, letterSpacing: 0.4 },
  cardDigitsWrap: { borderWidth: 1, borderRadius: 2, minHeight: 48, paddingHorizontal: 12, paddingVertical: 8, flexDirection: 'row', alignItems: 'center', gap: 10 },
  cardDigitsMask: { flex: 1 },
  cardDigitsMaskText: { fontSize: 12, fontWeight: FontWeight.black, letterSpacing: 2.2 },
  cardDigitsInput: { width: 54, fontSize: 16, fontWeight: FontWeight.black, letterSpacing: 2, textAlign: 'right', paddingVertical: 0 },
  selectorBtn: { borderWidth: 1, borderRadius: 2, paddingHorizontal: Spacing.md, paddingVertical: Spacing.md },
  selectorText: { fontSize: FontSize.sm, fontWeight: FontWeight.bold },
  metaSelectorBtn: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12 },
  metaSelectorLabel: { fontSize: 10, fontWeight: FontWeight.black, letterSpacing: 1 },
  metaSelectorValue: { fontSize: 12, fontWeight: FontWeight.black, letterSpacing: 0.3 },
  periodRow: { flexDirection: 'row', gap: 6, flexWrap: 'wrap' },
  periodBtn: { paddingHorizontal: 10, paddingVertical: 8, borderWidth: 1, borderRadius: 2 },
  periodBtnText: { fontSize: 10, fontWeight: FontWeight.black },
  dateModeToggle: { flexDirection: 'row', gap: 3, borderWidth: 1, borderRadius: 2, padding: 3 },
  dateModeBtn: { flex: 1, minHeight: 34, borderWidth: 1, borderRadius: 2, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
  dateModeText: { fontSize: 10, fontWeight: FontWeight.black, letterSpacing: 0.4 },
  calendarCard: { borderWidth: 1, borderRadius: 2, padding: 12, gap: 10 },
  calendarHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  calendarNavBtn: { width: 28, height: 28, borderWidth: 1, borderRadius: 2, alignItems: 'center', justifyContent: 'center' },
  calendarTitle: { fontSize: 12, fontWeight: FontWeight.black, letterSpacing: 0.8, textTransform: 'capitalize' },
  calendarWeekdays: { flexDirection: 'row' },
  calendarWeekday: { flex: 1, textAlign: 'center', fontSize: 10, fontWeight: FontWeight.black, letterSpacing: 0.6 },
  calendarGrid: { flexDirection: 'row', flexWrap: 'wrap', rowGap: 4 },
  calendarDay: { width: '14.2857%', alignItems: 'center', justifyContent: 'center', minHeight: 34, borderWidth: 1, borderRadius: 2 },
  calendarDayText: { fontSize: 12, fontWeight: FontWeight.bold },
  calendarSelectedText: { fontSize: 10, fontWeight: FontWeight.bold, letterSpacing: 0.8, textAlign: 'center' },
  checkboxRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 2 },
  checkboxBox: { width: 16, height: 16, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  checkboxTick: { fontSize: 10, fontWeight: FontWeight.black, lineHeight: 12 },
  checkboxLabel: { fontSize: 11, fontWeight: FontWeight.black, letterSpacing: 0.6, flex: 1 },
  notesInput: { minHeight: 110 },
  sheetOverlay: { ...StyleSheet.absoluteFillObject, justifyContent: 'flex-end' },
  sheetViewport: { width: '100%' },
  sheetCard: {
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderTopLeftRadius: 2,
    borderTopRightRadius: 2,
    padding: Spacing.base,
    gap: Spacing.xs,
  },
  dateSheetCard: {
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderTopLeftRadius: 2,
    borderTopRightRadius: 2,
    padding: Spacing.base,
    gap: Spacing.sm,
    maxHeight: '82%',
  },
  sheetHeader: { gap: 4, marginBottom: Spacing.xs },
  sheetTitle: { fontSize: FontSize.md, fontWeight: FontWeight.black, letterSpacing: 0.6 },
  sheetSubtitle: { fontSize: FontSize.xs, fontWeight: FontWeight.bold, letterSpacing: 0.8 },
  sheetOption: {
    borderWidth: 1,
    borderRadius: 2,
    padding: Spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sheetOptionLabel: { fontSize: 10, fontWeight: FontWeight.black, letterSpacing: 1.2 },
  sheetOptionValue: { fontSize: 16, fontWeight: FontWeight.black, marginTop: 2 },
  sheetOptionRadio: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetOptionDot: { width: 8, height: 8, borderRadius: 4 },
  sheetConfirmBtn: { borderRadius: 2, paddingVertical: Spacing.md, alignItems: 'center', marginTop: Spacing.xs },
  sheetConfirmText: { fontSize: FontSize.sm, fontWeight: FontWeight.black, letterSpacing: 0.8 },
  footerRow: { flexDirection: 'row', gap: Spacing.sm, marginTop: Spacing.sm },
  footerBtnSecondary: { flex: 1, borderWidth: 1, borderRadius: 2, paddingVertical: Spacing.md, alignItems: 'center' },
  footerBtnSecondaryText: { fontSize: FontSize.sm, fontWeight: FontWeight.black, letterSpacing: 0.8 },
  footerBtnPrimary: { flex: 1, borderRadius: 2, paddingVertical: Spacing.md, alignItems: 'center' },
  footerBtnPrimaryText: { fontSize: FontSize.sm, fontWeight: FontWeight.black, letterSpacing: 0.8 },
  footerBtnDisabled: { opacity: 0.6 },
});

