import { StyleSheet } from 'react-native';
import { Spacing, FontSize, FontWeight } from '../../../constants/theme';

const R = 2;
export const sty = StyleSheet.create({
  container: { flex: 1 },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.sm,
    borderBottomWidth: 1,
  },
  title: { fontSize: FontSize.md, fontWeight: FontWeight.black, letterSpacing: 0.5 },
  closeBtn: { padding: Spacing.xs },
  content: { padding: Spacing.base, gap: Spacing.md, paddingBottom: Spacing.xxxl },
  sectionLabel: { fontSize: 8, fontWeight: FontWeight.black, letterSpacing: 2, textTransform: 'uppercase' },
  hint: { fontSize: FontSize.xs, lineHeight: 18, marginTop: -Spacing.xs },
  presetsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.xs },
  presetBtn: {
    width: '31%',
    borderWidth: 1,
    borderRadius: R,
    padding: Spacing.sm,
    gap: Spacing.xs,
    position: 'relative',
  },
  presetPreview: {
    borderWidth: 2,
    borderRadius: R,
    padding: 6,
    minHeight: 34,
    justifyContent: 'center',
    gap: 3,
  },
  presetPreviewTopRow: { flexDirection: 'row', gap: 3, marginBottom: 1 },
  presetPreviewDot: { width: 10, height: 10, borderRadius: 2 },
  presetPreviewLine: { width: '100%', height: 2, borderRadius: 1 },
  presetPreviewLineShort: { width: '60%', height: 2, borderRadius: 1 },
  presetName: { fontSize: 9, fontWeight: FontWeight.black, letterSpacing: 0.5 },
  presetCheck: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewBoard: { borderWidth: 1, borderRadius: R, padding: Spacing.md, gap: Spacing.sm },
  previewCardLarge: { borderWidth: 1, borderRadius: R, padding: Spacing.md, gap: Spacing.sm },
  previewHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  previewOverline: { fontSize: 8, fontWeight: FontWeight.black, letterSpacing: 1.4 },
  previewBadge: { borderWidth: 1, borderRadius: R, paddingHorizontal: 5, paddingVertical: 2 },
  previewBadgeText: { fontSize: 7, fontWeight: FontWeight.black, letterSpacing: 0.8 },
  previewBalance: { fontSize: 24, fontWeight: FontWeight.black, letterSpacing: -0.8 },
  previewMetrics: { flexDirection: 'row', gap: Spacing.xs },
  previewMetric: { flex: 1, borderWidth: 1, borderRadius: R, padding: Spacing.sm, gap: 4 },
  previewMetricLabel: { fontSize: 8, fontWeight: FontWeight.black, letterSpacing: 1 },
  previewMetricValue: { fontSize: 12, fontWeight: FontWeight.black },
  previewGrid: { flexDirection: 'row', gap: Spacing.xs },
  previewCardSmall: { flex: 1, borderWidth: 1, borderRadius: R, padding: Spacing.md, gap: Spacing.xs },
  previewSmallValue: { fontSize: 20, fontWeight: FontWeight.black, letterSpacing: -0.6 },
  previewTrack: { height: 8, borderRadius: R, overflow: 'hidden' },
  previewFill: { height: '100%', borderRadius: R },
  previewCategoryRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  previewCategoryIcon: { width: 22, height: 22, borderWidth: 1, borderRadius: R },
  previewCategoryCopy: { flex: 1 },
  previewCategoryName: { fontSize: 12, fontWeight: FontWeight.black },
  previewCategoryMeta: { fontSize: 9, marginTop: 2 },
  previewRowItem: { borderWidth: 1, borderRadius: R, padding: Spacing.md, flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  previewRowIcon: { width: 28, height: 28, borderWidth: 1, borderRadius: R },
  previewRowCopy: { flex: 1 },
  previewRowValue: { fontSize: 12, fontWeight: FontWeight.black, marginTop: 2 },
  previewSwatchSet: { flexDirection: 'row', gap: 4 },
  previewTinySwatch: { width: 14, height: 14, borderWidth: 1, borderRadius: R },
  colorList: { borderWidth: 1, borderRadius: R, overflow: 'hidden' },
  colorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: Spacing.md,
    gap: Spacing.md,
    borderBottomWidth: 1,
  },
  colorRowLast: { borderBottomWidth: 0 },
  colorInfo: { flex: 1 },
  colorLabelRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  colorName: { fontSize: FontSize.sm, fontWeight: FontWeight.black },
  customBadge: {
    fontSize: 7,
    fontWeight: FontWeight.black,
    letterSpacing: 0.8,
    borderWidth: 1,
    borderRadius: R,
    paddingHorizontal: 4,
    paddingVertical: 1,
  },
  colorDesc: { fontSize: FontSize.xs, marginTop: 2 },
  colorHex: { fontSize: 9, marginTop: 2, letterSpacing: 0.5, fontWeight: '700' },
  colorSwatch: { width: 36, height: 36, borderRadius: R, borderWidth: 1, flexShrink: 0 },
  resetBtn: { borderWidth: 1, borderRadius: R, padding: Spacing.md, alignItems: 'center' },
  resetTxt: { fontSize: FontSize.sm, fontWeight: FontWeight.black, letterSpacing: 1 },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    padding: Spacing.lg,
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  modalCard: {
    borderWidth: 1,
    borderRadius: R,
    padding: Spacing.md,
    gap: Spacing.md,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: Spacing.sm,
  },
  modalCopy: { flex: 1, gap: 4 },
  modalTitle: { fontSize: FontSize.md, fontWeight: FontWeight.black, letterSpacing: 0.4 },
  modalDescription: { fontSize: FontSize.sm, lineHeight: 18 },
  modalPreview: {
    borderWidth: 1,
    borderRadius: R,
    padding: Spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  modalPreviewSwatch: { width: 42, height: 42, borderRadius: R, borderWidth: 1 },
  modalPreviewCopy: { flex: 1, gap: 2 },
  modalPreviewLabel: { fontSize: 8, fontWeight: FontWeight.black, letterSpacing: 1.1 },
  modalPreviewValue: { fontSize: FontSize.sm, fontWeight: FontWeight.black },
  modalSwatchGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  modalSwatch: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalSwatchActive: { transform: [{ scale: 1.08 }], borderWidth: 2.5 },
  modalActions: { flexDirection: 'row', gap: Spacing.sm },
  modalActionBtn: {
    flex: 1,
    minHeight: 42,
    borderWidth: 1,
    borderRadius: R,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: Spacing.sm,
  },
  modalActionText: { fontSize: 10, fontWeight: FontWeight.black, letterSpacing: 0.5 },
});

